### ISSUE TITLE
GetTransactions(uint start, uint end) does not work as intended

### ISSUE THREAD

**Issue by Blackcode** [dkackman/chia-dotnet#30]
GetTransactions(uint start, uint end) brings same values from last to first, different lengths.
Did multiple tests and did not managed to get my transactions in incremental mode.

![image](https://user-images.githubusercontent.com/516789/151154720-b71f3000-2cd1-48b3-9cf6-1a5acdecace3.png)
![image](https://user-images.githubusercontent.com/516789/151154451-b186addd-c5ac-4606-9b13-60fda2d76895.png)

PS: doing tests on alt coins network but that is not an issue.

**Comment by dkackman** [comment]
@Blackcode which chia branch are you using?

**Comment by Blackcode** [comment]
> @Blackcode which chia branch are you using?

not running chia but a hdd fork (https://github.com/HDDcoin-Network/hddcoin-blockchain)... should be forked from the latest chia main branch

**Comment by dkackman** [comment]
Looking like an issue in the RPC endpoint. Ill look in that code two, but this test fails where it seems to me like it shouldn't.

```csharp
var transactions1 = await _theWallet.GetTransactions(2, 4, cts.Token);
var transactions2 = await _theWallet.GetTransactions(4, 6, cts.Token);

Assert.IsNotNull(transactions1);
Assert.AreEqual(transactions1.Count(), 2);

var list1 = transactions1.ToList();
var start1 = list1[0];
var end1 = list1[1];

var list2 = transactions2.ToList();
var start2 = list2[0];
var end2 = list2[1];

Assert.AreNotEqual(start1.TransactionId, start2.TransactionId); //FAILS
Assert.AreNotEqual(end1.TransactionId, end2.TransactionId);
```

**Comment by dkackman** [comment]
> So what are you saying is that RPC endpoint (chia) is bugged or just HDDCoin?

I chatted in the chia keybase dev channel and looks like a bug in the 1.2.11 that is fixed in their main branch and slated for the next release. Looks like your hard fork will have to merge from there.

**Comment by Blackcode** [comment]
ok i will ask them if they can... thanks man

**Comment by dkackman** [comment]
Sounds good - gonna close this

**Comment by Blackcode** [comment]
Do you know what is the commit to fix this bug?

**Comment by dkackman** [comment]
> Do you know what is the commit to fix this bug?

Take a look at this pull request. I think this is the change they will need. https://github.com/Chia-Network/chia-blockchain/pull/9278
