### ISSUE TITLE
missing API: get_coin_records_by_hint

### ISSUE THREAD

**Issue by wizicer** [dkackman/chia-dotnet#44]
**Is your feature request related to a problem? Please describe.**

Missing API: get_coin_records_by_hint which seems added in v1.3 (sorry, seems my fault, the API is in main not in v1.3)

**Describe the solution you'd like**

I want this API be added.

**Describe alternatives you've considered**

Add this API.

**Additional context**

REF: https://github.com/Chia-Network/chia-blockchain/blob/main/chia/rpc/full_node_rpc_api.py#L57

**Comment by dkackman** [comment]
Thanks for the heads up though

**Comment by wizicer** [comment]
Latest release just added this RPC API.

REF: https://github.com/Chia-Network/chia-blockchain/releases/tag/1.3.4

**Comment by dkackman** [comment]
Give this a shot: https://www.nuget.org/packages/chia-dotnet/1.1.0
