### ISSUE TITLE
random null reference 

### ISSUE THREAD

**Issue by SalimiHabib** [dkackman/chia-dotnet#5]
we are using DI in .net core to inject  daemon in controller constructor but  **randomly** ended to null refrence in webSocket.SendAsync() method 

 ```
services.AddSingleton(sp =>
            {
                var daemon =
                    new chia.dotnet.Daemon(
                        chia.dotnet.Config.Open(@"C:\Users\kkkkkk\.chia\mainnet\config\config.yaml").GetEndpoint("daemon"),
                        "robin.pool.be");
             
                _ = daemon.Connect(CancellationToken.None);
                _ = daemon.Register(CancellationToken.None);

                return daemon;
            });
 

and ended to  
`    Object reference not set to an instance of an object.` in  webSocket.SendAsync()

**Comment by dkackman** [comment]
Some things to look at:

Do you have a call stack? 
The config is correct and cert path point correctly?

If you can provide a minimal reproducible example code set I can take a look next week. 

The fact that is coming out of the websocket code is odd.

**Comment by SalimiHabib** [comment]
it solved after update all nuggets in all projects .
 may be version conflict 
thank you

**Comment by dkackman** [comment]
Awesome!
