### ISSUE TITLE
Return types instead of dynamic

### ISSUE THREAD

**Issue by seertenedos** [dkackman/chia-dotnet#7]
It would be nice if if there was an option to get response back that were not dynamics so you know what to expect without needing to check docs, type safety and prevent developer errors. Dynamic does not have to go but it would be nice if there was a typed version as well

**Comment by dkackman** [comment]
Have been meaning to - im almost done with a refactor and then will look to this next

**Comment by seertenedos** [comment]
sounds great.  Of the 2 libs for dotnet yours has more of the methods supported which is great.

**Comment by dkackman** [comment]
I think it has complete or nearly complete coverage.  If you see gaps let me know.

**Comment by seertenedos** [comment]
not an enpoint that is missing but more a support thing it feels like you should have something like this class https://github.com/Playwo/ChiaRPC.Net/blob/master/ChiaRPC.Net/Utils/Bech32M.cs  to convert the puzzleHash to addresses and back.  apart from that i have not found anything else missing

**Comment by dkackman** [comment]
@seertenedos  take a look at https://github.com/dkackman/chia-dotnet/tree/static-types. It's about 80% complete but I'd love to get some more test coverage on it if you've got something you're working on.

**Comment by seertenedos** [comment]
@dkackman that looks great though i would use either List or ICollection on data stored in the types instead of IEnumerable.  IEnumerable can be interated over atleast once but maybe no more than that and it takes one interation just to get the size. For a lot of those collections i would just use IList instead of IEnumerable to make it easier for users of the lib to move around the collections. I mean this for things inside response objects not when the response itself is a list of objects.

I am workingon stuff working with the FullNode.  If you release it as a prerelease nuget i am happy to pull it down and test it in my usecase.

**Comment by seertenedos** [comment]
@dkackman may also move the entities/data structure classes to a subfolder to keep things cleaner

**Comment by dkackman** [comment]
> 
> 
> @dkackman may also move the entities/data structure classes to a subfolder to keep things cleaner

good idea

**Comment by dkackman** [comment]
> 
> 
> @dkackman that looks great though i would use either List or ICollection on data stored in the types instead of IEnumerable. IEnumerable can be interated over atleast once but maybe no more than that and it takes one interation just to get the size. For a lot of those collections i would just use IList instead of IEnumerable to make it easier for users of the lib to move around the collections. I mean this for things inside response objects not when the response itself is a list of objects.

I'll look at that.

> 
> I am workingon stuff working with the FullNode. If you release it as a prerelease nuget i am happy to pull it down and test it in my usecase.

Give this a try. Continued feedback welcome.
https://www.nuget.org/packages/chia-dotnet/0.4.0-alpha.1

**Comment by seertenedos** [comment]
@dkackman I updated my code to use the above nuget and found one bug so far.  Try testing "fullNode.GetAdditionsAndRemovals" the Addition and Removal lists have Coin in it but that is actually 1 more level down.  There should be a level above that and because of that all the values in the reponse for Additions and Removals are empty objects.

**Comment by dkackman** [comment]
> 
> 
> @dkackman I updated my code to use the above nuget and found one bug so far. Try testing "fullNode.GetAdditionsAndRemovals" the Addition and Removal lists have Coin in it but that is actually 1 more level down. There should be a level above that and because of that all the values in the reponse for Additions and Removals are empty objects.

Ah. They are `CoinRecord` not `Coin`. fix incoming.

**Comment by dkackman** [comment]
@seertenedos fix is here: https://www.nuget.org/packages/chia-dotnet/0.4.0-alpha.2 

I reviewed the python and `get_additions_and_removals` appears to be the only place where `CoinRecord` is used for additions instead of `Coin`. - also just noticed that those are still IEnumerable. Will change in next release.

**Comment by seertenedos** [comment]
@dkackman that looks good now

**Comment by dkackman** [comment]
I finished all of the full node method.  Which mens everything is done except the non standard wallets, which I don't have good test cases for. I'm going to play around with those next.

`dotnet add package chia-dotnet --version 0.4.0-alpha.3`
